import Head from "next/head";
import { useQuery } from "urql";
import { SimpleGrid } from "@chakra-ui/react";

import { PRODUCT_QUERY } from "../lib/query";
import Product from "../components/Product";
import Layout from "../layout/Layout";
import Loader from "../components/Loader";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <Loader />;
  if (error) return <p>Something went wrong...... {error.message}</p>;

  const products = data.products.data;
  console.log(products);

  return (
    <Layout>
      <Head>
        <title>E-commerce | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <SimpleGrid minChildWidth="18rem" w="full" h="full">
        {products?.map((product) => (
          <Product key={product.id} product={product.attributes} />
        ))}
      </SimpleGrid>
    </Layout>
  );
}
